---
# ROS install task

- name: Handles correct ROS distribution according to the Ubuntu version.
  include_vars: "{{ ansible_distribution_release }}.yml"

- name: Setup ROS keys
  apt_key:
    state: present
    url: "{{ ros_keyserver }}"

- name: Setup sources.list
  apt_repository:
    repo: deb {{ ros_repository_url }} {{ ansible_distribution_release }} main
    state: present
    filename: ros-latest

- name: Install ROS
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages: "{{ 'ros-' + ros_distribution + '-' + ros_configuration }}"

- name: Install python-rosdep 
  apt:
    name: "{{ (ros_distribution == 'noetic') | ternary('python3-rosdep','python-rosdep') }}"
    update_cache: yes

- name: Initialize rosdep
  command: rosdep init
  args:
    creates: /etc/ros/rosdep/sources.list.d/20-default.list

- name: Update rosdep
  command: rosdep update
  args:
    creates: /home/{{ ros_user.name }}/.ros/rosdep/sources.cache
  become: yes
  become_user: "{{ ros_user.name }}"

- name: Update .bashrc with /opt/ros/<ros_distribution>/setup.bash
  lineinfile:
    path: /home/{{ ros_user.name }}/.bashrc
    line: source /opt/ros/{{ ros_distribution }}/setup.bash

- name: Install dependencies for building packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - "build-essential"
    - "{{ (ros_distribution == 'noetic') | ternary('python3-rosinstall','python-rosinstall') }}"
    - "{{ (ros_distribution == 'noetic') | ternary('python3-rosinstall-generator','python-rosinstall-generator') }}"
    - "{{ (ros_distribution == 'noetic') | ternary('python3-wstool','python-wstool') }}"
    - "{{ (ros_distribution == 'noetic') | ternary('python3-catkin-tools','python-catkin-tools') }}"
    - "python3-colcon-common-extensions"
    - "python3-pip"

- name: Install Colcon Bundle
  pip:
    name: "{{ packages }}"
    executable: pip3
    extra_args: -U
  vars:
    packages:
    - colcon-ros-bundle
  tags:
    - pip3
