FROM ubuntu:xenial

RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y software-properties-common && rm -rf /var/lib/apt/lists/*

RUN apt-add-repository -y ppa:ansible/ansible && apt-get update && apt-get install -y \
    git \
    ansible \
 && rm -rf /var/lib/apt/lists/*

RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

RUN useradd -m -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 ubuntu


ENTRYPOINT ["/sbin/init"]
